# Generated by Django 3.0.6 on 2020-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='EMP_ID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='EMP_MOBILE',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='EMP_NAME',
            field=models.CharField(default='', max_length=200),
        ),
    ]
