# Generated by Django 3.0.6 on 2020-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200524_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUEST_NAME', models.CharField(default='', max_length=200)),
                ('GUEST_MOBILE', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
