# Generated by Django 3.0.6 on 2020-05-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='DEPARTMENT',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='TEMPERATURE',
            field=models.CharField(default='', max_length=5),
        ),
    ]
