# Generated by Django 3.0.6 on 2020-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200528_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_IP', models.CharField(max_length=200)),
                ('TEMPERATURE', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
