# Generated by Django 3.0.6 on 2020-05-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20200529_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='TEMPERATURE',
        ),
    ]
