# Generated by Django 3.0.6 on 2020-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20200529_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='EMP_IP',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
