# Generated by Django 3.0.6 on 2020-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20200529_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='EMP_IP',
        ),
        migrations.AddField(
            model_name='temperature',
            name='EMP_ID',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
