# Generated by Django 3.0.6 on 2020-06-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20200601_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='EMP_ID',
            field=models.ForeignKey(db_column='EMP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='employee.Employee'),
        ),
    ]
