# Generated by Django 3.0.6 on 2020-06-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20200601_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='EMP_ID',
            field=models.ForeignKey(db_column='EMP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.Employee'),
        ),
    ]
