# Generated by Django 3.0.6 on 2020-06-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20200601_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='EMP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Temperature', to='employee.Employee'),
        ),
    ]
