# Generated by Django 3.0.6 on 2020-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20200603_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='EMP_ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
